redis:
  host: localhost
  port: 6379
  namespace: huda
  db: 13
  
app:
  development:
    port: 4457
    host: "localhost"
    socket_port: 4457
  production:
    port: 4457
    host: "104.46.62.121"
    socket_port: 80

redis_keys:
  global:
    key: 'global_list'
    counter: 'global_counter'
    pubsub:
      list: 'pubsub_global_list'
      counter: 'pubsub_global_counter'
  tweets:
    key: 'tweets_list'
    counter: 'tweets_counter'
    pubsub:
      list: 'pubsub_tweets_list'
      counter: 'pubsub_tweets_counter'
    #max_count: 99
  pubsub:
    channel: 'realtime'
    tweet_channel: "tweets_realtime"

hashtags:
  twitter:
    - "العاصفة_هدى"
    - "Amman"
    - "العاصفة الثلجية"
    - "HudaStorm"
    - "Huda_in_Amman"
    - "ﻩﺩﻯ"
    - "عاصفة_هدى"
    - "لما_تثلج"
