redis:
  host: localhost
  port: 6379
  namespace: huda
  db: 13

redis_keys:
  global:
    key: 'global_list'
    counter: 'global_counter'
    pubsub:
      list: 'pubsub_global_list'
      counter: 'pubsub_global_counter'
  tweets:
    key: 'tweets_list'
    counter: 'tweets_counter'
    pubsub:
      list: 'pubsub_tweets_list'
      counter: 'pubsub_tweets_counter'
    #max_count: 99
  pubsub:
    channel: 'realtime'
    tweet_channel: "tweets_realtime"

hashtags:
  twitter:
    - "العاصفة_هدى"
    - "Amman"
    - "Jordan"
    - "HudaStorm"
    - "Huda_in_Amman"
    - "هدى"
    - "عاصفة_هدى"
